import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
	MatButtonModule,
	MatCheckboxModule,
	MatDatepickerModule,
	MatDialogModule,
	MatFormFieldModule,
	MatIconModule,
	MatInputModule,
	MatListModule,
	MatNativeDateModule,
	MatPaginatorModule,
	MatProgressBarModule,
	MatRadioModule,
	MatSelectModule,
	MatTableModule,
	MatToolbarModule,
	MatTooltipModule,
	MatProgressSpinnerModule,
	MatChipsModule,
	MatTabsModule,
	MatSortModule,
	MatStepperModule,
	MatMenuModule,
	MatCardModule,
	MatSlideToggleModule,
	MatExpansionModule
} from '@angular/material';

@NgModule({
	imports: [
		CommonModule,
		MatButtonModule,
		MatCheckboxModule,
		MatDatepickerModule,
		MatDialogModule,
		MatFormFieldModule,
		MatIconModule,
		MatInputModule,
		MatListModule,
		MatNativeDateModule,
		MatPaginatorModule,
		MatProgressBarModule,
		MatRadioModule,
		MatSelectModule,
		MatTableModule,
		MatToolbarModule,
		MatTooltipModule,
		MatProgressSpinnerModule,
		MatChipsModule,
		MatTabsModule,
		MatSortModule,
		MatStepperModule,
		MatMenuModule,
		MatCardModule,
		MatSlideToggleModule,
		MatExpansionModule
	],
	exports: [
		MatButtonModule,
		MatCheckboxModule,
		MatDatepickerModule,
		MatDialogModule,
		MatFormFieldModule,
		MatIconModule,
		MatInputModule,
		MatListModule,
		MatNativeDateModule,
		MatPaginatorModule,
		MatProgressBarModule,
		MatRadioModule,
		MatSelectModule,
		MatTableModule,
		MatToolbarModule,
		MatTooltipModule,
		MatProgressSpinnerModule,
		MatChipsModule,
		MatTabsModule,
		MatSortModule,
		MatStepperModule,
		MatMenuModule,
		MatCardModule,
		MatSlideToggleModule,
		MatExpansionModule
	]
})
export class MaterialModule {}
